RootyCommentBundle:
    resource: "@RootyCommentBundle/Controller/"
    type:     annotation
    prefix:   /
    
RootyUserBundle:
    resource: "@RootyUserBundle/Controller/"
    type:     annotation
    prefix:   /

RootyDefaultBundle:
    resource: "@RootyDefaultBundle/Resources/config/routing.yml"
    prefix:   /

RootyTorrentBundle:
    resource: "@RootyTorrentBundle/Controller/"
    type: annotation
    prefix: /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    
_imagine:
    resource: .
    type:     imagine

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

_index:
    pattern: /
    defaults: {_controller: RootyDefaultBundle:Default:index}
